[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

# Use Ubuntu Noble 24.04 build image
[build.processing]
  skip_processing = false

# Force Ubuntu Noble 24.04 build image
[context.production]
  command = "npm run build"

# Specify build image (this ensures Ubuntu Noble 24.04)
[build]
  base = ""
  
# Build image specification
[template.environment]
  NETLIFY_BUILD_IMAGE = "ubuntu-noble-24.04"

# Cache headers - shorter cache time for favicons to allow faster updates
[[headers]]
  for = "/favicon*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    
[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=3600"
